# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Choucas_visibility
                                 A QGIS plugin
 Calcul de visibilité et des incertitudes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-07-08
        copyright            : (C) 2019 by Choucas
        email                : Mohssine.Kaouadji@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Choucas'
__date__ = '2019-07-08'
__copyright__ = '(C) 2019 by Choucas'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                        QgsFeatureSink,
                        QgsProcessingException,
                        QgsProcessingAlgorithm,
                        QgsProcessingParameterRasterLayer,
                        QgsProcessingParameterFeatureSource,
                        QgsProcessingParameterFeatureSink,
                        QgsProcessingParameterNumber,
                        QgsProcessingParameterRasterDestination,
                        QgsWkbTypes)
import processing


class Choucas_visibilityAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    #INPUT_Active_viewshed = 'INPUT_Active_viewshed'
    INPUT_Hobs = 'Hobs'
    INPUT_DBH = 'INPUT_DBH'

    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # les données et les paramètres en entrée

        #self.addParameter(QgsProcessingParameterRasterLayer(self.INPUT_Active_viewshed, 'INPUT_Active_viewshed'))

        self.addParameter(QgsProcessingParameterRasterLayer(self.INPUT_DBH, 'INPUT_DBH'))

        self.addParameter(QgsProcessingParameterNumber(self.INPUT_Hobs, 'Hauteur d observation',QgsProcessingParameterNumber.Double,1.60))

        self.addParameter(QgsProcessingParameterRasterDestination(self.OUTPUT,"OUTPUT",None, False))

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        #raster_active_viewshed = self.parameterAsRasterLayer(parameters, self.INPUT_Active_viewshed, context)
        #raster_dbh = self.parameterAsRasterLayer(parameters, self.INPUT_DBH, context)
        Hobs=parameters[self.INPUT_Hobs]

        # DBH<=H
        formule='A <='+str(Hobs)
        #calculate


        #calcul du passive viewshed
        algresult =processing.run("gdal:rastercalculator",
        {'INPUT_A':parameters[self.INPUT_DBH],
        'BAND_A':1,
        'INPUT_B':None,
        'BAND_B':1,
        'INPUT_C':None,
        'BAND_C':-1,
        'INPUT_D':None,
        'BAND_D':-1,
        'INPUT_E':None,
        'BAND_E':-1,
        'INPUT_F':None,
        'BAND_F':-1,
        'FORMULA':formule,
        'NO_DATA':None,
        'RTYPE':2,
        'OPTIONS':'',
        'OUTPUT':parameters[self.OUTPUT]},
        context=context, feedback=feedback, is_child_algorithm=True)

        viewshed = algresult['OUTPUT']

        return {self.OUTPUT: viewshed}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Calcul de la vision passive'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Calcul de la vision passive à partir du DBH')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'visibilite_passive_stage'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Choucas_visibilityAlgorithm()
