# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ClassName
                                 A QGIS plugin
 Description du plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-11-20
        copyright            : (C) 2019 by Cécile Duchêne, ENSG
        email                : cecile.duchene@ensg.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Charles d\'Andigne et Amina Barmani, ENSG, IGN, LaSTIG'
__date__ = '2019-11-20'
__copyright__ = '(C) 2019 by Charles d\'Andigne et Amina Barmani, ENSG, IGN, LaSTIG'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'


import os
import processing
from qgis.PyQt.QtCore import (QCoreApplication,QVariant)
from qgis.core import (QgsProcessing,
                       QgsProcessingMultiStepFeedback,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber,
                       QgsProcessingOutputLayerDefinition,
                       QgsFeature,
                       QgsField,
                       QgsFields,
                       QgsWkbTypes,
                       QgsVectorLayer,
                       QgsProject,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterVectorDestination,
                       QgsProcessingOutputFolder,
                       QgsProcessingOutputFile,
                       QgsProcessingParameterFolderDestination,
                       QgsRasterLayer,
                       )


class Algo2(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    INPUT = 'INPUT'
    INPUT_MNT='INPUT_MNT'
    OUTPUT = 'OUTPUT_VIEWPOINTS'
    OUTPUT_FOLDER = 'OUTPUT_FOLDER'


    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT,
                self.tr('Couche de point'),
                [QgsProcessing.TypeVectorPoint]
            )
        )
        # MNT
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT_MNT,
                self.tr('Modèle Numérique de terrain')
            )
        )
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        #Couche de points de vue
        self.addParameter(
            QgsProcessingParameterVectorDestination(
                self.OUTPUT,
                self.tr('Couche point de vue ')
            )
        )
        ## OUTPUT_FOLDER dossier pour les outputs
        self.addParameter(
            QgsProcessingParameterFolderDestination(
                self.OUTPUT_FOLDER,
                "Dossier pour stocker les DBHs et les zones de visibilité"))


    def processAlgorithm(self, parameters, context, model_feedback):
        """
        Here is where the processing itself takes place.
        """
        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.

        #couches en entrée
        points = self.parameterAsVectorLayer(parameters,self.INPUT, context)
        mnt = self.parameterAsRasterLayer(parameters,self.INPUT_MNT, context)

        # couche de points de vue
        output_viewpoints = self.parameterAsOutputLayer(parameters, "OUTPUT_VIEWPOINTS", context)
        output_folder=self.parameterAsFile(parameters,"OUTPUT_FOLDER",context)




        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / points.featureCount() if points.featureCount() else 0


        print('Avant traitement')

        # variables propres à Processing
        feedback = QgsProcessingMultiStepFeedback(
            points.featureCount() * 2, model_feedback
        )

        # Verification d'u attribut ID
        if points.fields().indexOf("ID") < 0:
            feedback.reportError(
                "Les points doivent avoir un attribut numérique ID unique", True,
            )
            return {}

        #lancer l'algorithm de création des points de vue
        result=processing.runAndLoadResults("Choucas:Création de point de vue",
                       {'OBSERVER_POINTS': points,
                        'DEM': mnt,
                        'OBSERVER_ID': 'ID',
                        'RADIUS': 5000,
                        'RADIUS_FIELD': None,
                        'OBS_HEIGHT': 0,
                        'OBS_HEIGHT_FIELD': None,
                        'TARGET_HEIGHT': 0,
                        'TARGET_HEIGHT_FIELD': None,
                        'OUTPUT': output_viewpoints})['OUTPUT']

        print(result)
        layer_viewPoints = QgsVectorLayer(result, 'test', "ogr")
        print(layer_viewPoints.isValid())
        QgsProject.instance().addMapLayer(layer_viewPoints)

        #nombre de point de vue
        pts_count = layer_viewPoints.featureCount()
        print(pts_count)

        #définir la liste des zones de visibilités
        liste_VisiPass=[]

        #Lancer l'algo de calcul de DBH et de zones de visibilité
        for i in range(0,pts_count):
            # input
            partie1 = result + "|layerid=0|subset=\"ID\" = \'"
            point_obs_id = partie1 + str(i+1) + "\'"

            # output

            dbh_output = output_folder + '/DBH' + str(i+1) + '.tif'
            passive_output = output_folder + '/Passive' + str(i+1) + '.tif'


            processing.run(
                "Choucas:Calcul de la vision active, passive et le raster depth below horizon à partir du point d observation et du MNT ",
                {'OBSERVER_POINTS': point_obs_id,
                 'Hobs': 1.6,
                 'DEM': mnt,
                 'USE_CURVATURE': True,
                 'REFRACTION': 0.13,
                 'OUTPUT_DBH': dbh_output,
                 'OUTPUT_PASSIVE': passive_output})

            # Ajouter les rasters dans la liste
            raster = QgsRasterLayer(passive_output, 'passive');
            liste_VisiPass.append(raster)

        print(liste_VisiPass)
        #Concatenation par calculatrice raster
        output_Visi_Pts = output_folder + '/Concatenation_Visi_Passive_Pts.tif';
        #Cas n=3

        if len(liste_VisiPass)==3:
            parameters = {'INPUT_A': liste_VisiPass[0],
                          'INPUT_B': liste_VisiPass[1],
                          'INPUT_C': liste_VisiPass[2],
                          'BAND_A': 1,
                          'BAND_B': 1,
                          'BAND_C': 1,
                          'FORMULA': '(A * B * C )', #  expression here.
                          'OUTPUT': output_Visi_Pts}

            processing.runAndLoadResults('gdal:rastercalculator', parameters)

        print('Après traitement')
        """
        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # *** Ici appeler la methode qui construit l'objet modifié (ou créé) en sortie
            # à partir de l'objet en entrée (variable feature) ***
            # Il faudra alors remplacer dans la ligne ci-dessous la variable "feature"
            # par la variable contenant l'objet en sortie
            # Pour l'instant on met juste un petit message pour dire qu'on passe par là

            


            # Update the progress bar
            feedback.setProgress(int(current * total))
            """

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        #return {self.OUTPUT: dest_id}
        return {self.OUTPUT:layer_viewPoints}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Visibilite_passive_pts_aleatoires'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'visibilite_surface_partielle_pir'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Algo2()
